In [1]:
import torch

#Tensor is a multi-dimentional array that can use GPU - reason for this is numpy doesn't use GPU
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [5]:
# torch variant of numpy
x = torch.zeros([2,5])
print(x)
print(x.shape)


y = torch.rand([2,5])
print(y)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([2, 5])
tensor([[0.5488, 0.8823, 0.1592, 0.8813, 0.3452],
        [0.8587, 0.3030, 0.8220, 0.7036, 0.4817]])


In [7]:
#Numpy Reshape -> View
#Flatten operation - used in Nerual networks to 1 by 10 array rather than 2 by 5 array
y_flattened = y.view([1,10])
print(y_flattened)

tensor([[0.5488, 0.8823, 0.1592, 0.8813, 0.3452, 0.8587, 0.3030, 0.8220, 0.7036,
         0.4817]])
